[package]
name = "tlv0838"
version = "0.1.0"
edition = "2021"
liense = "MIT"
description="embedded_hal driver for TI's TLV0838 ADC chip"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.7"
